version: 2
jobs:
  build:
    docker:
      - image: kriasoft/node-ci:9.1.0-alpine
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --production true

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run: yarn test

      - deploy:
          name: Deploying to s3s
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_DEPLOY_BRANCH}" ]; then
              ./bin/deploy.sh production
            elif [ "${CIRCLE_BRANCH}" == "${STAGING_DEPLOY_BRANCH}" ]; then
              ./bin/deploy.sh staging
            else
              echo "Nothing to deploy for this branch"
            fi
